library(tm)
library(wordcloud)
text <- readLines(file.choose())
docs <- Corpus(VectorSource(text))
docs <- tm_map(docs, tolower)
docs <- tm_map(docs, removeNumbers)
docs <- tm_map(docs, removePunctuation) 
docs <- tm_map(docs, removeWords, stopwords("spanish"))
docs <- tm_map(docs, stripWhitespace)               
toSpace <- content_transformer(function(x, pattern)gsub(pattern, " ", x))
docs <- tm_map(docs, toSpace, "/")
docs <- tm_map(docs, toSpace, "?")
docs <- tm_map(docs, toSpace, ".")
docs <- tm_map(docs, toSpace, ",")
docs <- tm_map(docs, toSpace, "@")
docs <- Corpus(VectorSource(text))
dtm <- TermDocumentMatrix(docs)
m <- as.matrix(dtm)
v <- sort(rowSums(m), decreasing=TRUE)
d <- data.frame(word=names(v), freq= v)
head(d,10)
wordcloud(words=d$word, freq= d$freq, min.freq=1, max.words=10, random.order=FALSE, rot.per = 1, colors=brewer.pal(8, "Dark2"))
